In [170]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle as pkl

In [171]:
book = pd.read_csv('Books.csv')
rating = pd.read_csv('Ratings.csv')
user =pd.read_csv('Users.csv')

C:\Users\vivek\AppData\Local\Temp\ipykernel_28884\3191663332.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  book = pd.read_csv('Books.csv')

In [172]:
book.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [173]:
books=book.drop(['Image-URL-S','Image-URL-L'],axis=1)

In [174]:
rating.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [175]:
user.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [176]:
book.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271360 entries, 0 to 271359
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ISBN                 271360 non-null  object
 1   Book-Title           271360 non-null  object
 2   Book-Author          271358 non-null  object
 3   Year-Of-Publication  271360 non-null  object
 4   Publisher            271358 non-null  object
 5   Image-URL-S          271360 non-null  object
 6   Image-URL-M          271360 non-null  object
 7   Image-URL-L          271357 non-null  object
dtypes: object(8)
memory usage: 16.6+ MB

In [177]:
rating.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1149780 entries, 0 to 1149779
Data columns (total 3 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   User-ID      1149780 non-null  int64
 1   ISBN         1149780 non-null  object
 2   Book-Rating  1149780 non-null  int64
dtypes: int64(2), object(1)
memory usage: 26.3+ MB

In [178]:
user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278858 entries, 0 to 278857
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   User-ID   278858 non-null  int64
 1   Location  278858 non-null  object
 2   Age       168096 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 6.4+ MB

In [179]:
book.duplicated().sum()

np.int64(0)

In [180]:
rating.duplicated().sum()

np.int64(0)

In [181]:
user.duplicated().sum()

np.int64(0)

Popularity based recommonation model

In [193]:
rating_with_book=rating.merge(book,on='ISBN')

In [194]:
count_rating_with_book=rating_with_book.groupby('Book-Title').count()[['Book-Rating']].reset_index()

In [195]:
count_rating_with_book.rename(columns={'Book-Rating':'count_rating'},inplace=True)

In [196]:
count_rating_with_book=count_rating_with_book[count_rating_with_book['count_rating'] >=250]

In [197]:
final_df=count_rating_with_book.merge(rating_with_book,on='Book-Title')

In [198]:
top=final_df.groupby('Book-Title')['Book-Rating'].mean().sort_values(ascending=False).reset_index().rename(columns={'Book-Rating':'avg_rating'})

In [199]:
top

                                            Book-Title  avg_rating
0    Harry Potter and the Prisoner of Azkaban (Book 3)    5.852804
1         Harry Potter and the Goblet of Fire (Book 4)    5.824289
2       Harry Potter and the Sorcerer's Stone (Book 1)    5.737410
3    Harry Potter and the Order of the Phoenix (Boo...    5.501441
4     Harry Potter and the Chamber of Secrets (Book 2)    5.183453
..                                                 ...         ...
181       Vinegar Hill (Oprah's Book Club (Paperback))    2.245283
182                                           Whispers    2.199301
183                                  Presumed Innocent    2.139456
184                                       Isle of Dogs    2.000000
185                                        Wild Animus    1.019584

[186 rows x 2 columns]

In [200]:
top_50_books=top.merge(books,on=['Book-Title']).sort_values(ascending=False , by='avg_rating').drop_duplicates('Book-Title')[:50]

In [201]:
top_50_books.shape

(50, 7)

In [202]:
top_50_books

,Book-Title,avg_rating,ISBN,Book-Author,Year-Of-Publication,Publisher,Image-URL-M
0,Harry Potter and the Prisoner of Azkaban (Book 3),5.852804,0439136350,J. K. Rowling,1999,Scholastic,http://images.amazon.com/images/P/0439136350.0...
3,Harry Potter and the Goblet of Fire (Book 4),5.824289,0439139597,J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439139597.0...
5,Harry Potter and the Sorcerer's Stone (Book 1),5.737410,0590353403,J. K. Rowling,1998,Scholastic,http://images.amazon.com/images/P/0590353403.0...
11,Harry Potter and the Order of the Phoenix (Boo...,5.501441,0439358078,J. K. Rowling,2004,Scholastic Paperbacks,http://images.amazon.com/images/P/0439358078.0...
13,Harry Potter and the Chamber of Secrets (Book 2),5.183453,0439064872,J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439064872.0...
16,The Hobbit : The Enchanting Prelude to The Lor...,5.007117,0345339681,J.R.R. TOLKIEN,1986,Del Rey,http://images.amazon.com/images/P/0345339681.0...
22,The Fellowship of the Ring (The Lord of the Ri...,4.948370,0618260269,J. R. R. Tolkien,2002,Houghton Mifflin Company,http://images.amazon.com/images/P/0618260269.0...
26,Harry Potter and the Sorcerer's Stone (Harry P...,4.895652,059035342X,J. K. Rowling,1999,Arthur A. Levine Books,http://images.amazon.com/images/P/059035342X.0...
34,"The Two Towers (The Lord of the Rings, Part 2)",4.880769,0618260277,J. R. R. Tolkien,2002,Houghton Mifflin Company,http://images.amazon.com/images/P/0618260277.0...
45,To Kill a Mockingbird,4.700000,157270036X,Harper Lee,1997,Audio Partners,http://images.amazon.com/images/P/157270036X.0...
48,The Da Vinci Code,4.642539,0739307312,DAN BROWN,2003,Random House Audio,http://images.amazon.com/images/P/0739307312.0...
53,The Five People You Meet in Heaven,4.551163,0786868716,Mitch Albom,2003,Hyperion,http://images.amazon.com/images/P/0786868716.0...
59,The Catcher in the Rye,4.545657,0531001725,Jerome David Salinger,1973,Scholastic Library Pub,http://images.amazon.com/images/P/0531001725.0...
62,The Lovely Bones: A Novel,4.468726,0316666343,Alice Sebold,2002,"Little, Brown",http://images.amazon.com/images/P/0316666343.0...
67,1984,4.454225,848328006X,George Orwell,1997,"Plaza &amp; Janes Editores, S.A.",http://images.amazon.com/images/P/848328006X.0...
72,Prodigal Summer: A Novel,4.450593,0060959037,Barbara Kingsolver,2001,Perennial,http://images.amazon.com/images/P/0060959037.0...
73,Neverwhere,4.449057,0380789019,Neil Gaiman,1998,Avon,http://images.amazon.com/images/P/0380789019.0...
81,The Secret Life of Bees,4.447028,0670032379,Sue Monk Kidd,2002,Viking Books,http://images.amazon.com/images/P/0670032379.0...
84,Stupid White Men ...and Other Sorry Excuses fo...,4.356890,0060392452,Michael Moore,2002,Regan Books,http://images.amazon.com/images/P/0060392452.0...
85,"Tuesdays with Morrie: An Old Man, a Young Man,...",4.354970,0385484518,MITCH ALBOM,1997,Doubleday,http://images.amazon.com/images/P/0385484518.0...
88,The Red Tent (Bestselling Backlist),4.334716,0312195516,Anita Diamant,1998,Picador USA,http://images.amazon.com/images/P/0312195516.0...
93,The Hitchhiker's Guide to the Galaxy,4.328358,0517542099,Douglas Adams,1989,Harmony,http://images.amazon.com/images/P/0517542099.0...
98,Nickel and Dimed: On (Not) Getting By in America,4.289552,0805063897,Barbara Ehrenreich,2002,Owl Books,http://images.amazon.com/images/P/0805063897.0...
100,Into the Wild,4.273810,0385486804,Jon Krakauer,1997,Anchor,http://images.amazon.com/images/P/0385486804.0...
110,Fahrenheit 451,4.264059,0345320328,Ray Bradbury,1979,Del Rey Books,http://images.amazon.com/images/P/0345320328.0...
116,Girl with a Pearl Earring,4.218631,0452282152,Tracy Chevalier,2001,Plume Books,http://images.amazon.com/images/P/0452282152.0...
120,Outlander,4.173145,0385302304,DIANA GABALDON,1991,Delacorte Press,http://images.amazon.com/images/P/0385302304.0...
123,Where the Heart Is (Oprah's Book Club (Paperba...,4.105983,0446672211,Billie Letts,1998,Warner Books,http://images.amazon.com/images/P/0446672211.0...
124,Seabiscuit: An American Legend,4.098182,0449005615,LAURA HILLENBRAND,2002,Ballantine Books,http://images.amazon.com/images/P/0449005615.0...
126,Life of Pi,4.088855,0151008116,Yann Martel,2002,Harcourt,http://images.amazon.com/images/P/0151008116.0...
132,The Bean Trees,4.087404,0060158638,Barbara Kingsolver,1988,Harpercollins,http://images.amazon.com/images/P/0060158638.0...
133,"A Child Called \It\"": One Child's Courage to S...",4.086792,1558743669,Dave Pelzer,1995,Health Communications,http://images.amazon.com/images/P/1558743669.0...
135,ANGELA'S ASHES,4.075269,0684874350,Frank McCourt,1996,Scribner,http://images.amazon.com/images/P/0684874350.0...
137,Good in Bed,4.055102,0743418174,Jennifer Weiner,2002,Washington Square Press,http://images.amazon.com/images/P/0743418174.0...
139,Fast Food Nation: The Dark Side of the All-Ame...,4.037383,0060938455,Eric Schlosser,2002,Perennial,http://images.amazon.com/images/P/0060938455.0...
140,American Gods,4.006623,0380789035,Neil Gaiman,2002,HarperTorch,http://images.amazon.com/images/P/0380789035.0...
141,Skipping Christmas,4.006211,0385505833,JOHN GRISHAM,2001,Doubleday,http://images.amazon.com/images/P/0385505833.0...
147,Left Behind: A Novel of the Earth's Last Days ...,4.003145,0842329129,Tim Lahaye,1996,Tyndale House Publishers,http://images.amazon.com/images/P/0842329129.0...
153,"The Golden Compass (His Dark Materials, Book 1)",4.000000,0440418321,PHILIP PULLMAN,2001,Yearling,http://images.amazon.com/images/P/0440418321.0...
157,The Color Purple,3.964968,0671617028,Alice Walker,1985,Pocket Books,http://images.amazon.com/images/P/0671617028.0...
165,Silence of the Lambs,3.960938,0749324082,Thomas Harris,1997,Mandarin,http://images.amazon.com/images/P/0749324082.0...
166,About a Boy,3.900763,1573227331,Nick Hornby,1999,Riverhead Books,http://images.amazon.com/images/P/1573227331.0...
173,Seven Up (A Stephanie Plum Novel),3.888489,0312265840,Janet Evanovich,2001,St. Martin's Press,http://images.amazon.com/images/P/0312265840.0...
176,The Alchemist: A Fable About Following Your Dream,3.875940,0062502182,Paulo Coelho,1995,HarperSanFrancisco,http://images.amazon.com/images/P/0062502182.0...
177,Hard Eight : A Stephanie Plum Novel (A Stephan...,3.825279,0312983867,Janet Evanovich,2003,St. Martin's Paperbacks,http://images.amazon.com/images/P/0312983867.0...
182,Suzanne's Diary for Nicholas,3.820569,0316969443,James Patterson,2001,"Little, Brown",http://images.amazon.com/images/P/0316969443.0...
191,Lord of the Flies,3.818533,0698102193,William G. Golding,1978,Putnam Pub Group,http://images.amazon.com/images/P/0698102193.0...
192,A Prayer for Owen Meany,3.796610,0345361792,John Irving,1990,Ballantine Books,http://images.amazon.com/images/P/0345361792.0...
194,"The Vampire Lestat (Vampire Chronicles, Book II)",3.777409,0345313860,ANNE RICE,1986,Ballantine Books,http://images.amazon.com/images/P/0345313860.0...
195,White Oleander : A Novel (Oprah's Book Club),3.772472,0316284955,Janet Fitch,2000,Back Bay Books,http://images.amazon.com/images/P/0316284955.0...

In [192]:
pkl.dump(top_50_books,open('top50books.pkl','wb'))